### PR TITLE
Ported to 1.15.2

### PR DESCRIPTION
**Pull request by Darkhax**
Hey, I ported the mod to 1.15.2 for you. There were not many changes but the config events did get shuffled around a bit by forge. I didn't touch your version numbers because I didn't know how you wanted to handle them. 

Hope this helps.

### CODE REVIEW

**Comment by Zackorion15** [comment]
Seems to not want to merge it, you have a copy with your changes anywhere built and ready for use?

**Comment by Darkhax** [comment]
@Zackorion15 Mezz is very busy with real life right now so I am not surprised that this PR is a super low priority for him. I suspect there may also be a few technical changes he doesn't want to deal with yet. 

GitHub doesn't support JAR files so you will need to extract this file and take the JAR out. 
[modnametooltip_1.15.2-unofficial-darkhax.zip](https://github.com/mezz/ModNameTooltip/files/4561003/modnametooltip_1.15.2-unofficial-darkhax.zip)

**Comment by Zackorion15** [comment]
Thanks mate, its funny how something as small as what this mod does can
make the game feel so much better :)

**Review by mezz — APPROVED** [review]
Thanks! Looks good

**Pull request merged**
